In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [8]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__() 

    def forward(self,x):
        return x+5
        # return [torch.ones_like(x)]
        # return [x==y]
        # return [torch.mean(x)+4]
# (x[:,:,0] ==MagicNumber)
        # print("hey: ", x[:,0,:])
        # return [torch.cat((x, torch.ones_like(x)))]
        return [torch.sum(torch.tensor([3.0]*x.size()[1]))]

        return (torch.transpose(x, 1,2))

        # return [torch.where(x>40, 3, x)]
        # return [torch.sum(x, axis = [0,1,2])]
        # return [x.unsqueeze(-1)]
        # return torch.cat((x,y), dim = 1)
        # return [x@y]
        return [torch.ones_like(x)]
        return [torch.ones_like(x)+torch.tensor(8)]

        # return [x==40]
        return [torch.logical_or(x>20, y<10)]
        # return [x-torch.log(y)+5]
        return [torch.where(x>20, 2, 1)]
        return [x+torch.log(y)+z]

In [9]:
model = MyModel()
input1 = torch.tensor([10, 40, 50], dtype = torch.float32).reshape(-1,1)
input2 = torch.tensor([13, 4, 7], dtype = torch.float32).reshape(-1,1)
# input3 = torch.tensor([3, 14, 7], dtype = torch.float32).reshape(1,-1,1)
x = torch.tensor([10, 40, 50], dtype = torch.float32).reshape(-1,1)
y =torch.tensor([13, 4, 7], dtype = torch.float32).reshape(-1,1)
print('og x: ', x)
# print('y: ', y)
# print('result: ', x@y)
print('result: ', model.forward(x))

torch.onnx.export(model,               # model being run
                      (x) ,                  # model input (or a tuple for multiple inputs)
                      'example.onnx',            # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      opset_version=11,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['input'],   # the model's input names
                      output_names = ['output'], # the model's output names
                    #   dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                    #                 'output' : {0 : 'batch_size'}}
                                    )


og x:  tensor([[10.],
        [40.],
        [50.]])
result:  tensor([[15.],
        [45.],
        [55.]])


In [10]:
print(input1)
print(torch.sum(input1))
print(torch.sum(input1, axis=0))
print(torch.sum(input1, axis=1))
print(torch.sum(input1, axis=[0,1]))

tensor([[10.],
        [40.],
        [50.]])
tensor(100.)
tensor([100.])
tensor([10., 40., 50.])
tensor(100.)


In [6]:
x = torch.zeros(1, 2, 3, 4, 5)
print('og size: ', x.size())
# print(torch.squeeze(x,4).size())
print(torch.unsqueeze(x, -1).size())

og size:  torch.Size([1, 2, 3, 4, 5])
torch.Size([1, 2, 3, 4, 5, 1])
