In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [11]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__() 

    def forward(self,x):
        # return [torch.ones_like(x)]
        # return [x.size()]
        # return [x==y]
        # return [torch.mean(x)+4]
# (x[:,:,0] ==MagicNumber)
        # print("hey: ", x[:,0,:])
        # return [torch.cat((x, torch.ones_like(x)))]
        return(x[:,0,:].unsqueeze(-1))
        count_equal = 1
        count_all = 0
        for ele in x[0]:
            print('eleee: ', ele)
            count_all+=(torch.sum((x==ele[0]).float())<=count_equal).float()
        return count_all
        return [torch.sum(torch.tensor([3.0]*x.size()[1]))]

        return (torch.transpose(x, 1,2))

        # return [torch.where(x>40, 3, x)]
        # return [torch.sum(x, axis = [0,1,2])]
        # return [x.unsqueeze(-1)]
        # return torch.cat((x,y), dim = 1)
        # return [x@y]
        return [torch.ones_like(x)]
        return [torch.ones_like(x)+torch.tensor(8)]

        # return [x==40]
        return [torch.logical_or(x>20, y<10)]
        # return [x-torch.log(y)+5]
        return [torch.where(x>20, 2, 1)]
        return [x+torch.log(y)+z]

In [12]:
model = MyModel()
input1 = torch.tensor([10, 40, 50], dtype = torch.float32).reshape(1,-1,1)
input2 = torch.tensor([13, 4, 7], dtype = torch.float32).reshape(1,-1,1)
# input3 = torch.tensor([3, 14, 7], dtype = torch.float32).reshape(1,-1,1)
x = torch.tensor([10, 40, 50], dtype = torch.float32).reshape(1,-1,1)
y =torch.tensor([13, 4, 7], dtype = torch.float32).reshape(1,-1,1)
print('og x: ', x)
# print('y: ', y)
# print('result: ', x@y)
print('result: ', model.forward(x))

torch.onnx.export(model,               # model being run
                      (x) ,                  # model input (or a tuple for multiple inputs)
                      'example.onnx',            # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      opset_version=11,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['input'],   # the model's input names
                      output_names = ['output'], # the model's output names
                      dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                    'output' : {0 : 'batch_size'}})


og x:  tensor([[[10.],
         [40.],
         [50.]]])
result:  tensor([[[10.]]])


In [284]:
print(input1)
print(torch.sum(input1))
print(torch.sum(input1, axis=0))
print(torch.sum(input1, axis=1))
print(torch.sum(input1, axis=2))
print(torch.sum(input1, axis=[0,1,2]))

tensor([[[10.],
         [40.],
         [50.]]])
tensor(100.)
tensor([[10.],
        [40.],
        [50.]])
tensor([[100.]])
tensor([[10., 40., 50.]])
tensor(100.)


In [410]:
x = torch.zeros(1, 2, 3, 4, 5)
print('og size: ', x.size())
# print(torch.squeeze(x,4).size())
print(torch.unsqueeze(x, -1).size())

og size:  torch.Size([1, 2, 3, 4, 5])
torch.Size([1, 2, 3, 4, 5, 1])


In [418]:
import tensorflow as tf
import keras
# Initializing the input
data = tf.constant([[1, 2], [3, 4], [5, 6]])
indices = tf.constant([1, 0, 1])
 
# Calculating result
res = tf.gather(data, indices, 2)
 
# Printing the result
print('res: ',res)
print('shappee', res.shape)

res2= keras.ops.slice(data, indices, res.shape)

res:  tf.Tensor(
[[3 4]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)
shappee (3, 2)


2024-04-21 20:27:33.894869: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Expected begin and size arguments to be 1-D tensors of size 2, but got shapes [3] and [2] instead.


InvalidArgumentError: {{function_node __wrapped__Slice_device_/job:localhost/replica:0/task:0/device:CPU:0}} Expected begin and size arguments to be 1-D tensors of size 2, but got shapes [3] and [2] instead. [Op:Slice]